import Head from 'next/head';
import { Inter } from 'next/font/google';
import Header from '@/components/Header';
// import Explore from '@/components/Explore';
import ChooseUs from '@/components/ChooseUs';
import Slider from 'react-slick';
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { keyframes } from "@chakra-ui/react";
import QRCode from 'react-qr-code';


import {
  Accordion,
  Box,
  Button,
  Flex,
  Grid,
  Heading,
  Img,
  Modal,
  ModalBody,
  ModalCloseButton,
  ModalContent, 
  ModalHeader,
  ModalOverlay,
  Text,
  useDisclosure,
} from '@chakra-ui/react';
import Question from '@/components/Question';
import Footer from '@/components/Footer';
import ServiceButton from '@/components/ServiceButton';
import { useEffect, useState } from 'react';
import Review from '@/components/Review';
import { useRouter } from 'next/router';

export default function Home() {
  useEffect(() => {
    window.addEventListener('scroll', handleScroll);
    return () => {
      window.removeEventListener('scroll', handleScroll);
    };
  }, []);
  useEffect(() => {
    const storedCheckSum = localStorage.getItem('paymentCheckSum');
    const storedTranscationId = localStorage.getItem('transactionIddd');

    console.log('CheckSum is ', storedCheckSum);
    console.log('transactionId is ', storedTranscationId);
  }, []);

  const { onOpen, onClose, isOpen } = useDisclosure();
  const [activeSection, setActiveSection] = useState(null);
  const router = useRouter();

  const settings = {
    dots: true,
    infinite: true,
    speed: 700,
    slidesToShow: 1,
    slidesToScroll: 1,
    autoplay: true,
    autoplaySpeed: 3000,
    pauseOnHover: true,
    arrows: true,
    responsive: [
      {
        breakpoint: 1024, // Desktop and large screens
        settings: {
          arrows: true,
          dots: true,
        },
      },
      {
        breakpoint: 768, // Tablets
        settings: {
          arrows: false,
          dots: true,
        },
      },
      {
        breakpoint: 480, // Mobile
        settings: {
          arrows: false,
          dots: true,
        },
      },
    ],
  };

  const slides = [
    'images/Slider1.png',
    'images/Slider2.png',
    'images/Slider3.png',
    'images/Slider4.png',
    'images/Slider5.png',
    'images/Slider6.png',
    'images/Slider7.png',
  ];
  const handleScroll = () => {
    const scrollPosition = window.scrollY;
    const homeSection = document.getElementById('home');
    const aboutSection = document.getElementById('about');    const faqSection = document.getElementById('faq');
    const contactSection = document.getElementById('contact');

    if (
      scrollPosition >= homeSection?.offsetTop &&
      scrollPosition < aboutSection?.offsetTop
    ) {
      setActiveSection('home');
    } else if (
      scrollPosition >= aboutSection?.offsetTop &&
      scrollPosition < faqSection?.offsetTop
    ) {
      setActiveSection('about');
    } else if (
      scrollPosition >= faqSection?.offsetTop &&
      scrollPosition < contactSection?.offsetTop
    ) {
      setActiveSection('faq');
    } else if (scrollPosition >= contactSection?.offsetTop) {
      setActiveSection('contact');
    } else {
      setActiveSection(null);
    }
  };

  const scaleAnimation = keyframes`
from {
  transform: scale(1);
}
to {
  transform: scale(1.1);
}
`;
const slideFromTop = keyframes`
  0% {
    transform: translateY(-100%);
    opacity: 0;
  }
  100% {
    transform: translateY(0);
    opacity: 1;
  }
`;
const slideFromLeft = keyframes`
  from {
    transform: translateX(-100%);
    opacity: 0;
  }
  to {
    transform: translateX(0);
    opacity: 1;
  }
`;

const slideFromRight = keyframes`
  from {
    transform: translateX(100%);
    opacity: 0;
  }
  to {
    transform: translateX(0);
    opacity: 1;
  }
`;

const slideFromBottom = keyframes`
  from {
    transform: translateY(100%);
    opacity: 0;
  }
  to {
    transform: translateY(0);
    opacity: 1;
  }
`;
const flipAnimation = keyframes`
  0% {
    transform: rotateY(0);
  }
  50% {
    transform: rotateY(90deg);
  }
  100% {
    transform: rotateY(0);
  }
`;

const bounceAnimation = keyframes`
  0%, 100% {
    transform: translateY(0);
  }
  50% {
    transform: translateY(-10px);
  }
`;

// Optional pulsing effect
const pulseAnimation = keyframes`
  0% {
    transform: scale(1);
  }
  50% {
    transform: scale(1.1);
  }
  100% {
    transform: scale(1);
  }
`;


  return (
    <>
      <Head>
        <title>YellowSense</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="images/logo.webp" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@0,300;0,400;0,700;0,900;1,300;1,400;1,700;1,900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main>
      <Box id="yellowsense" bg="#F5F5F5" padding="2px">
        <Header activeSection={activeSection} />
      </Box>
    
      <Box id="yellowsense" bg="#F5F5F5" py={{ base: '4', md: '8' }}>
      <Flex justify="center" mb="4">
        <Box
          as="h2"
          fontSize={{ base: 'xl', md: '3xl' }}
          fontWeight="bold"
          color="#A15942"
          textAlign="center"
        >
          Welcome to YellowSense
        </Box>
      </Flex>
     
      <Box
        px={{ base: '2', md: '6' }}
        py={{ base: '4', md: '6' }}
        boxShadow="lg"
        borderRadius="lg"
        overflow="hidden"
        bg="white"
      >
        <Slider {...settings}>
          {slides.map((image, index) => (
            <Box key={index}>
              <img
                src={image}
                alt={`Slide ${index + 1}`}
                style={{
                  width: '100%',
                  height: 'auto',
                  objectFit: 'cover',
                  maxHeight: '700px',
                }}
              />
            </Box>
          ))}
        </Slider>
      </Box>
    </Box>
        <Flex
          id="home"
          bgGradient="linear(to-br, #FFF1D0, #FFFFFF)"
          justifyContent="center"
          gap="10%"
        >
        
          <Box
            my={{ md: '20vh', base: '10vh' }}
            w={{ md: '30%', base: '100%' }}
            px={{ base: '5%', md: '0' }}
            bgImage={{
              base: "linear-gradient(rgba(0, 0, 0, 0.527),rgba(0, 0, 0, 0.5)) , url('images/mobileBg.webp')",
              md: '',
            }}
            bgSize="cover"
            color={{ md: 'black', base: 'white' }}
          >
            <Flex
              alignItems="center"
              borderRadius="20px"
              cursor="pointer"
              onClick={() =>
                router.push(
                  'https://play.google.com/store/apps/details?id=in.yellowsense_jobs'
                )
              }
              justifyContent="center"
              mt={{ md: '5%', base: '13%' }}
              color={{ md: 'white', base: 'black' }}
              bg={{ md: '#AD6A4D', base: '#F8B728' }}
              p="2%"
            >
              <Img w="7%" src="images/naukri.webp" />
              <Text>नौकरी पायें |</Text> <Img w="7%" src="images/rozgar.webp" />
              <Text>रोज़गार पायें |</Text> <Img w="7%" src="images/earn.webp" />
              <Text>कमाई करे</Text>
            </Flex>
            <Heading fontSize={{ md: '3.5rem', base: '2.5rem' }} pt="5%">
              Booking{' '}
              <Text color={{ md: '#A15942', base: 'yellow' }} display="inline">
                Maid, Cook, Nanny
              </Text>{' '}
              even got <Text>easier</Text>
            </Heading>
            <Button
              p="5% 10%"
              borderRadius="15px"
              bg="#F8B728"
              my="8%"
              _hover={{ backgroundColor: '#F6CD74' }}
              boxShadow="rgba(232, 169, 33, 0.6) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px;"
              onClick={onOpen}
            >
              Book Now
            </Button>
            <Text>
              We're building an AI-powered platform for quick connections
              between customers and housekeepers like maids,cooks and nannies.
              One click links customers with these workers, offering employment
              opportunities for those in need.
            </Text>

            <Modal
              isOpen={isOpen}
              onClose={onClose}
              isCentered
              size={{ md: 'xl', base: 'xs' }}
              preserveScrollBarGap
            >
              <ModalOverlay />
              <ModalContent borderRadius="30px">
                <ModalHeader bg="#FFED9B" pb="0px" borderRadius="30px">
                  <Flex alignItems="center" justifyContent="space-between">
                    <Heading size={{ md: 'xl', base: 'md' }} color="#a15942">
                      Choose a service
                    </Heading>
                    <Img
                      w="40%"
                      src="images/rectangle-2660@2x.webp"
                      alt="service"
                    />
                  </Flex>
                </ModalHeader>
                <ModalCloseButton />
                <ModalBody>
                  <Flex
                    justifyContent="space-between"
                    flexDirection={{ md: 'row', base: 'column' }}
                  >
                    <ServiceButton image="images/maid.webp" person="Maid" />
                    <ServiceButton image="images/cook.webp" person="Cook" />
                    <ServiceButton image="images/nanny.webp" person="Nanny" />
                  </Flex>
                </ModalBody>
              </ModalContent>
            </Modal>
          </Box>
          <Box
            w="29rem"
            h="30rem"
            my="20vh"
            position="relative"
            display={{ base: 'none', md: 'block' }}
            
          >
            <Box
              w="23rem"
              h="80%"
              position="absolute"
              borderRadius="30px 70px"
              bgGradient="linear(to-b, #A15942, transparent)"
              right="0"
              animation={`${slideFromRight} 1s ease-out`}
              _hover={{
                animation: `${scaleAnimation} 0.5s ease-in-out forwards`,
              }}
            />
            <Box
              w="23rem"
              h="80%"
              bg="yellow"
              borderRadius="30px 70px"
              zIndex={1}
              border="8px solid white"
              left="3rem"
              top="3rem"
              position="absolute"
              animation={`${slideFromTop} 1s ease-out`}
              _hover={{
                animation: `${scaleAnimation} 0.5s ease-in-out forwards`,
              }}
            >
              <Img
                h="100%"
                objectFit="cover"
                borderRadius="30px 70px"
                src="images/landing.webp"
                alt="landing"
              />
            </Box>
            <Box
              w="23rem"
              h="80%"
              position="absolute"
              borderRadius="30px 70px"
              bg="#A15942"
              bottom={0}
              animation={`${slideFromLeft} 1s ease-out`}
              _hover={{
                animation: `${scaleAnimation} 0.5s ease-in-out forwards`,
              }}
            />
          </Box>
        </Flex>
        {/* <Explore /> */}
        
        
          {/* <Heading
            fontSize={{ md: '1.8rem', base: '1.8rem' }}
            color="#A15942"
            py="3%"
          >
            Download The App
          </Heading>
          <Img
            py="3%"
            w="200px"
            boxShadow="white 0px 5px 15px"
            cursor="pointer"
            borderRadius="20px"
            onClick={() =>
              router.push(
                'https://play.google.com/store/apps/details?id=com.yellowsense'
              )
            }
            src="images/google.svg"
            alt="googlePlay"
            animation={`${slideFromBottom} 1s ease-out`}
              _hover={{
                animation: `${scaleAnimation} 0.5s ease-in-out forwards`,
              }}
          /> */}
             <Flex
          alignItems="center"
          justifyContent="center"
          gap="5%"
          py="3%"
          bg="#FFFFE9"
          flexDirection={{ base: 'column', md: 'row' }}
        >
      <Heading
        fontSize={{ md: '1.8rem', base: '1.8rem' }}
        color="#A15942"
        py="3%"
      >
        Download The App
      </Heading>
      
      <Img
        py="3%"
        w="200px"
        boxShadow="white 0px 5px 15px"
        cursor="pointer"
        borderRadius="20px"
        onClick={() =>
          router.push(
            'https://play.google.com/store/apps/details?id=com.yellowsense'
          )
        }
        src="images/google.svg"
        alt="Google Play"
        animation={`${slideFromBottom} 1s ease-out`}
        _hover={{
          animation: `${scaleAnimation} 0.5s ease-in-out forwards`,
        }}
      />

      <Flex direction="column" align="center" mt="3%">
        <Heading fontSize="1rem" color="#A15942" mb="2%">
          Scan to Download
        </Heading>
        <QRCode value={'https://play.google.com/store/apps/details?id=com.yellowsense'} size={150} />
      </Flex>
  
        </Flex>
        <Box id="about" bg="#FFFFE9">
          <Heading
            fontSize={{ md: '3.5rem', base: '2.5rem' }}
            color="#A15942"
            textAlign="center"
          >
            About Us
          </Heading>
          <Flex p="5%" alignItems="center" justifyContent="center" gap="10%">
            <Box w={{ md: '40%', base: '90%' }}>
              <Text
                fontSize={{ md: '1.5rem', base: '1rem' }}
                bgImage={{ base: "url('images/aboutLogo.webp')", md: '' }}
                bgSize={{ base: 'contain' }}
                bgRepeat={{ base: 'no-repeat' }}
                bgPosition="center"
                animation={`${flipAnimation} 1.5s ease-in-out`}
                _hover={{
                  animation: `${flipAnimation} 1.5s ease-in-out`,
                }}
                style={{
                  transformStyle: "preserve-3d", // Ensure 3D perspective
                  backfaceVisibility: "hidden", // Hide the back when flipped
                }}
              >
                The current challenge lies in securing readily available
                domestic help such as maids, cooks, and nannies, leading to a
                significant gap between supply and demand. Conversely, service
                providers in this sector struggle to find suitable employment
                opportunities. What is required is a platform that effectively
                connects service seekers with service providers, addressing this
                imbalance.
                  {/* The current challenge lies in securing readily
                available domestic help such as maids, cooks, and nannies,
          leading to a significant gap between supply and demand.*/}   
              </Text>
            </Box>

            <Img
              w="30%"
              display={{ base: 'none', md: 'block' }}
              borderRadius="30px 100px"
              src="images/yellowsense.webp"
              alt="logo"
              animation={`${bounceAnimation} 1.5s infinite`}
              _hover={{
                animation: `${pulseAnimation} 1s infinite`,
              }}
              
            />
          </Flex>
        </Box>

        <Flex
          py="5%"
          id="testimonials"
          alignItems="center"
          direction="column"
          bg="#FFFFE9"
        >
          <Heading
            fontSize={{ md: '2.5rem', base: '1.8rem' }}
            color="#A15942"
            mb="5%"
            textAlign="center"
          >
            What Our Client Says
          </Heading>
          <Flex
            pt="5%"
            justifyContent="space-around"
            flexDirection={{ md: 'row', base: 'column' }}
            w="90%"
          >
            <Review
              photo="images/user1.webp"
              name="Manish Kumar"
              status="Entrepreneur and Food Lover"
              words="Being an entrepreneur often means long hours and little time for personal chores, especially cooking. Thankfully, YellowSense's cook service has been a godsend. The chef they've assigned is not just a good cook but also an expert in preparing authentic Indian dishes that remind me of my mother's cooking. Each meal is a delightful journey through the flavors of India. I highly recommend YellowSense to anyone craving delicious home-cooked meals without the hassle."
            />
            <Review
              photo="images/user2.webp"
              name="Neha R."
              status="Working Professional and Homemaker"
              words="Juggling a career and household responsibilities can be exhausting, but YellowSense has been a game-changer for me. Their maid service not only keeps my home sparkling clean but also adds that special touch of traditional Indian hospitality. The cook they've provided understands our regional cuisine preferences perfectly, whipping up mouthwatering dishes that taste just like home. And when it comes to childcare, their nanny service has been a blessing during my busiest days. I'm grateful for the peace of mind they bring to my family."
            />
            <Review
              photo="images/user3.webp"
              name="Ananya S."
              status="Software Engineer"
              words="Transitioning into parenthood is a beautiful yet challenging journey, and YellowSense's nanny service has been my saving grace. The nanny they've provided is like an elder sister to our little one, showering her with love and care while ensuring her safety and development. Her understanding of  parenting customs and traditions has made the transition smoother for our family. Thanks to YellowSense, I can confidently navigate this new chapter of my life with support I can trust."
            />
          </Flex>
        </Flex>
        <ChooseUs />
        <Flex
          py="5%"
          alignItems="center"
          id="registered"
          bg="#FFFFE9"
          direction="column"
        >
          <Heading
            fontSize={{ md: '2.5rem', base: '1.8rem' }}
            color="#A15942"
            mb="5%"
          >
            Registered with
          </Heading>
          <Flex
            w="80%"
            alignItems="center"
            justifyContent="space-between"
            flexWrap="wrap"
          >
            <Img
              w={{ md: '12%', base: '40%' }}
              src="images/10008.webp"
              alt="registered"
            />
            <Img
              w={{ md: '12%', base: '40%' }}
              src="images/10009.webp"
              alt="registered"
            />
            <Img
              w={{ md: '12%', base: '40%' }}
              src="images/10010.webp"
              alt="registered"
            />
            <Img
              w={{ md: '12%', base: '40%' }}
              src="images/10011.webp"
              alt="registered"
            />
            <Img
              w={{ md: '12%', base: '40%' }}
              src="images/10012.webp"
              alt="registered"
            />
            <Img
              w={{ md: '12%', base: '40%' }}
              src="images/10013.webp"
              alt="registered"
            />
          </Flex>
        </Flex>

        <Flex
          py={{ md: '5%', base: '10%' }}
          alignItems="center"
          id="faq"
          bg="#FFFFE9"
          direction="column"
        >
          <Heading
            fontSize="2.5rem"
            color="#A15942"
            mb={{ md: '2%', base: '8%' }}
          >
            FAQ’s
          </Heading>
          <Accordion allowMultiple w={{ md: '80%', base: '90%' }}>
            <Question
              question="How does the booking process work?"
              answer="To book the worker, simply visit our website or mobile app, select the type of cleaning service you need, choose a date and time that works for you, and provide any specific instructions or preferences. Once your booking is confirmed, a worker will be assigned to your appointment."
            />
            <Question
              question="What if I need to cancel or reschedule my booking?"
              answer="You can easily cancel or reschedule your booking through our website or app up to a certain time before your appointment. Please refer to our cancellation policy for more details."
            />
            <Question
              question="How do you handle feedback or issues with the cleaning service?"
              answer="We value your feedback and strive to provide excellent service every time. If you have any concerns or issues with your cleaning service, please contact our customer support team, and we will promptly address them to your satisfaction."
            />
            <Question
              question="What areas do you serve?"
              answer="We currently serving in Bangalore and are continuously expanding to new locations. Please check our website or app for the most up-to-date information on service availability."
            />
          </Accordion>
        </Flex>
        <Footer />
      </main>
    </>
  );
}
